define(function (require, exports, module) {
  var pdf = require('pdf');
  var $ = require('jquery');
  var template = require('art-template');
  module.exports = {
    load: function () {
      var data={
        list:[
          {
            name:'报告概述',
            children:[]
          },
          {
            name:'基本信息',
            children:[
              {
                name:'工商信息'
              },
              {
                name:'股东信息'
              },
              {
                name:'主要人员'
              },
              {
                name:'分支机构'
              },
              {
                name:'变更记录'
              }
            ]
          },
          {
            name:'经营行为',
            children:[
              {
                name:'融资信息'
              },
              {
                name:'知识产权'
              },
              {
                name:'资质证书'
              },
              {
                name:'税务评级'
              },
              {
                name:'公开招聘'
              }
            ]
          },
          {
            name:'经营风险',
            children:[
              {
                name:'行政处罚'
              },
              {
                name:'经营异常'
              },
              {
                name:'严重违法'
              },
              {
                name:'动产抵押'
              },
              {
                name:'股权出质'
              }
            ]
          },
          {
            name:'关联关系',
            children:[
              {
                name:'股东关系'
              },
              {
                name:'投资关系'
              }
            ]
          },
          {
            name:'涉诉行为',
            children:[
              {
                name:'法院公告'
              },
              {
                name:'裁判文书'
              }
            ]
          },
          {
            name:'附注',
            children:[]
          }
        ]
      };
      $('#report-catalog-info').html(template('catalog-tp',data));
      pdf.addWaterMark($('.watermark'));
    }
  };
});
